python exp_train.py --exp-name "pretext_classification with PLAD" \
                    --task pretext_classification \
                    --data MSL \
                    --positive-augmentor-time 1217_1743 \
                    --perturbator-time 0105_2006 \
                    --constant-dim-amplitude-method inter \
                    --deviation-mode abs \
                    --non-constant-dim-tau 0.1 \
                    --constant-dim-tau 0.95 \
                    --perturbator-mode plad \
                    --positive-augmentor-noise-more True \
                    --seed 1